import {
  Injectable,
  Logger,
  OnModuleDestroy,
  OnModuleInit,
  ServiceUnavailableException,
} from "@nestjs/common";
import { PrismaPg } from "@prisma/adapter-pg";
// Generated by the `apiClient` generator in /prisma/schema.prisma
// (run `npm run prisma:generate` in apps/api).
import { PrismaClient } from "../../generated/prisma";
import { hasUsableDatabaseUrl } from "../config/env";

/**
 * PrismaService — wraps PrismaClient with the same pg driver adapter the
 * Next.js app uses (src/lib/prisma.ts), so both backends connect identically.
 *
 * Phase 0 keeps the "no database configured" graceful mode: the service boots
 * without a DATABASE_URL and reports unavailability instead of crashing.
 * Feature modules added in later phases access the client via `this.client`,
 * which throws a 503 if the database is not configured.
 */
@Injectable()
export class PrismaService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(PrismaService.name);
  private _client: PrismaClient | null = null;

  get client(): PrismaClient {
    if (!this._client) {
      throw new ServiceUnavailableException(
        "Database is not configured. Set DATABASE_URL for the API.",
      );
    }
    return this._client;
  }

  isAvailable(): boolean {
    return this._client !== null;
  }

  async onModuleInit() {
    if (!hasUsableDatabaseUrl()) {
      this.logger.warn(
        "DATABASE_URL missing or invalid — starting without a database connection.",
      );
      return;
    }

    const adapter = new PrismaPg({
      connectionString: process.env.DATABASE_URL,
    });

    this._client = new PrismaClient({
      adapter,
      log:
        process.env.NODE_ENV === "development"
          ? ["error", "warn"]
          : ["error"],
    });

    await this._client.$connect();
    this.logger.log("Connected to PostgreSQL via Prisma.");
  }

  async onModuleDestroy() {
    if (this._client) {
      await this._client.$disconnect();
    }
  }

  /** Lightweight connectivity probe used by the health endpoint. */
  async ping(): Promise<boolean> {
    if (!this._client) return false;
    try {
      await this._client.$queryRaw`SELECT 1`;
      return true;
    } catch {
      return false;
    }
  }
}
