import {
  Inject,
  Injectable,
  Logger,
  Optional,
  ServiceUnavailableException,
} from "@nestjs/common";
import { PrismaD1 } from "@prisma/adapter-d1";
import type { D1Database } from "@cloudflare/workers-types";
// Generated by the `apiClient` generator in /prisma/schema.prisma
// (run `npm run prisma:generate` in apps/api).
import { PrismaClient } from "../generated/prisma/client";

/** Injection token for the Cloudflare Worker `env.asp_db` binding. */
export const D1_DATABASE_BINDING = Symbol("D1_DATABASE_BINDING");

/**
 * PrismaService keeps Cloudflare-specific adapter setup at the infrastructure
 * boundary. Feature services continue to consume `this.prisma.client` and do
 * not need to know about D1.
 *
 * The optional injection point is for the future Worker bootstrap to provide
 * `env.asp_db`. Until that bootstrap exists, conventional Node startup remains
 * available for build/static checks but database access returns 503.
 */
@Injectable()
export class PrismaService {
  private readonly logger = new Logger(PrismaService.name);
  private _client: PrismaClient | null = null;
  private _binding: D1Database | null = null;

  constructor(
    @Optional()
    @Inject(D1_DATABASE_BINDING)
    binding?: D1Database,
  ) {
    if (binding) this.bind(binding);
  }

  get client(): PrismaClient {
    if (!this._client) {
      throw new ServiceUnavailableException(
        "Database is not configured. Provide the asp_db D1 binding.",
      );
    }
    return this._client;
  }

  isAvailable(): boolean {
    return this._client !== null;
  }

  /** Native binding reserved for the narrow D1 atomic-operation layer. */
  get binding(): D1Database {
    if (!this._binding) {
      throw new ServiceUnavailableException(
        "Database is not configured. Provide the asp_db D1 binding.",
      );
    }
    return this._binding;
  }

  /**
   * Configure the service from the Worker environment binding. The future
   * fetch/bootstrap adapter may either provide the injection token or call
   * this once while initializing an isolate.
   */
  bind(binding: D1Database): void {
    if (this._client) return;

    this._binding = binding;
    const adapter = new PrismaD1(binding);
    this._client = new PrismaClient({
      adapter,
    });
    this.logger.log("Prisma configured with the asp_db D1 binding.");
  }

  /** Lightweight connectivity probe used by the health endpoint. */
  async ping(): Promise<boolean> {
    if (!this._client) return false;
    try {
      await this._client.$queryRaw`SELECT 1`;
      return true;
    } catch {
      return false;
    }
  }
}
